export const WEATHER_FORECAST_FETCH_WEATHER = 'WEATHER_FORECAST/FETCH_WEATHER';
export const WEATHER_FORECAST_FETCH_WEATHER_PENDING = 'WEATHER_FORECAST/FETCH_WEATHER_PENDING';
export const WEATHER_FORECAST_FETCH_WEATHER_SUCCESS = 'WEATHER_FORECAST/FETCH_WEATHER_SUCCESS';
export const WEATHER_FORECAST_FETCH_WEATHER_ERROR = 'WEATHER_FORECAST/FETCH_WEATHER_ERROR';
