export const ASYNC_COUNTER_INCREMENT = 'ASYNC_COUNTER/INCREMENT';
export const ASYNC_COUNTER_DECREMENT = 'ASYNC_COUNTER/DECREMENT';
export const ASYNC_COUNTER_INCREMENT_ASYNC = 'ASYNC_COUNTER/INCREMENT_ASYNC';
