export const HELLO_WORLD_CHANGE_GREETING = 'HELLO_WORLD/CHANGE_GREETING';
export const HELLO_WORLD_CHANGE_SUBJECT = 'HELLO_WORLD/CHANGE_SUBJECT';
export const HELLO_WORLD_ADD_TODO = 'HELLO_WORLD/ADD_TODO';
export const HELLO_WORLD_TOGGLE_TODO = 'HELLO_WORLD/TOGGLE_TODO';
